spring:
  datasource:
    url: jdbc:sqlserver://azure-server-01.database.windows.net:1433;database:EmpDB;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: shikhar
    password: nagarro0SQL
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191